language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start
  - sleep 1
install: "pip install -r harvester/requirements.txt"
# command to run tests
before_script: cd harvester
script: python manage.py test
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5432
  - DJANGO_POSTGRES_HOST=127.0.0.1
  - DJANGO_POSTGRES_USER=postgres
  - DJANGO_POSTGRES_PASSWORD=
  - ELASTIC_SEARCH_USERNAME=search
  - ELASTIC_SEARCH_PASSWORD=qwerty
