version: '3'

services:
  harvester:
    build: .
    command: uwsgi --ini /usr/src/app/uwsgi.ini --py-autoreload=3 --honour-stdin
    volumes:
      - ./harvester:/usr/src/app
      - ./${HARVESTER_DATA_DIR}/:/usr/src/data
      - ./${HARVESTER_MEDIA_ROOT}/:/usr/src/media
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ELASTIC_SEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}

  postgres:
    image: postgres:11.1
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: pol
      PGDATA: /var/lib/postgresql/data/pgdata
      DJANGO_POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
    volumes:
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:
