version: '3'

services:
  harvester:
    image: registry.surfedu.nl/edu/pol-harvester:latest
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure
    networks:
      - webnet
      - default
    healthcheck:
      test: curl -sS http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  postgres:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure

  redis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  tasks:
    image: registry.surfedu.nl/edu/pol-harvester:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 10G
      restart_policy:
        condition: on-failure
    volumes:
     - /home/surf/kaldi:/home/surf/kaldi
     - /home/surf/Kaldi_NL:/home/surf/Kaldi_NL

  adminer:  # kills adminer in production, but the port should also be closed by the firewall
    command: "true"
    entrypoint: "true"
    deploy:
      restart_policy:
        condition: none

  metabase:
    image: metabase/metabase
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - JAVA_TIMEZONE=Europe/Amsterdam
    ports:
      - 3000:3000

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - cluster.name=elastic
      - xpack.security.enabled=true
      #- xpack.security.transport.ssl.enabled=true
      - xpack.security.audit.enabled=true
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=https://surfpol.nl
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 0
        window: 0s
    ports:
      - 9200:9200

volumes:
  postgres-data:
  metabase-data:
  elastic-data:

networks:
  webnet:
