version: '3.7'

services:

  harvester:
    build: .
    command: uwsgi --ini /usr/src/app/uwsgi.ini --py-autoreload=3 --honour-stdin
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
      - "redis"
    labels:
      nl.surfpol.harvester: "harvester"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ELASTIC_SEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}

  tasks:
    build: .
    command: celery -A pol_harvester worker --loglevel=info
    volumes:
      # Mounts we need to access local file and data storage
      - ${HARVESTER_DATA_DIR}/:/usr/src/data
      - ${HARVESTER_MEDIA_ROOT}/:/usr/src/media
      # Mounts we need for easy access to tools inside container
      - ./shell/.ipython/:/home/app/.ipython
      - ./shell/.bash_history:/home/app/.bash_history
    depends_on:
      - "postgres"
      - "redis"
    labels:
      nl.surfpol.tasks: "tasks"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=postgres
      - DJANGO_POSTGRES_PASSWORD=${DJANGO_POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ELASTIC_SEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME}
      - ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}
      - ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL}
      - ELASTIC_SEARCH_HOST=${ELASTIC_SEARCH_HOST}

  postgres:
    image: postgres:11
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: pol
      PGDATA: /var/lib/postgresql/data/pgdata
      DJANGO_POSTGRES_PASSWORD: ${DJANGO_POSTGRES_PASSWORD}
    labels:
      nl.surfpol.db: "postgres"
    volumes:
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres-data:/var/lib/postgresql/data/pgdata
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  postgres-data:
