version: '3'

services:
  harvester:
    image: registry.surfedu.nl/edu/pol-harvester:latest
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1G
      restart_policy:
        condition: on-failure
    networks:
      - webnet
      - default
    healthcheck:
      test: curl -sS http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

  postgres:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G
      restart_policy:
        condition: on-failure

  redis:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  tasks:
    image: registry.surfedu.nl/edu/pol-harvester:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4"
          memory: 10G
      restart_policy:
        condition: on-failure
    volumes:
     - /home/surf/kaldi:/home/surf/kaldi
     - /home/surf/Kaldi_NL:/home/surf/Kaldi_NL

  adminer:  # kills adminer in production, but the port should also be closed by the firewall
    command: "true"
    entrypoint: "true"
    deploy:
      restart_policy:
        condition: none

volumes:
  postgres-data:

networks:
  webnet:
