name: surf-harvester
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda
  - nb_conda_kernels
  - notebook
  - pip
  - pip:
    - -r harvester/requirements.txt
    - autopep8==1.3.5
    - jupyter-contrib-core==0.3.3
    - jupyter-nbextensions-configurator==0.4.0
    - click==7.0
    - toolz==0.9.0
    - invoke==1.2.0
    - clam==2.4.5
