name: surf-harvester
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=10.0.1=py36_0
  - python=3.6.6
  - uwsgi
  - libiconv
  - gcc
  - lxml
  - beautifulsoup4
  - urlobject
  - youtube-dl
  - conda-forge::spacy
  - protobuf
  - cython
  # cld3 installable through source: https://github.com/houp/cld3
  - pip:
    - django==1.11.18
    - jsonschema==2.6.0
    - whitenoise==4.0
    - pytz==2018.5
    - django-bootstrap4==0.0.7
    - ipdb==0.11
    - urlobject==2.4.3
    - pandas
    - pillow
    - git+https://github.com/fako/django-json-field.git
    - git+https://github.com/nickdavidhaynes/spacy-cld.git@2eb659d956924e26b47cba9e2c2a8ce3ebfe8b1f  # broken inside Conda for some reason
    - https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-2.0.0/nl_core_news_sm-2.0.0.tar.gz
